org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

floralis=10.6.0
forge=47.2.32
minecraft=1.20.1
parchment=2023.09.03

cofhcore=4970669
create=4835191
enderio=5171872
immersiveengineering=5224387
industrialforegoing=5355551
jade=5339264
jei=5101366
mekanism=5125665
patchouli=4966125
thermalcultivation=4970697
thermaldynamics=4970699
thermalexpansion=4970700
thermalfoundation=4979840
thermalinnovation=4970704
thermalintegration=4970705
thermallocomotion=4970706
titanium=4984333