modLoader="javafml"
loaderVersion="[42,)"
license="MIT License"
[[mods]]
modId="floralis"
version="${file.jarVersion}"
displayName="Floralis"
logoFile="logo.png"
authors="luxtracon"
description='''Floralis adds farmable cacti and flowers for an automatable way to obtain all dyes.'''

[[dependencies.floralis]]
modId="forge"
mandatory=true
versionRange="[42,)"
ordering="NONE"
side="BOTH"

[[dependencies.floralis]]
modId="minecraft"
mandatory=true
versionRange="[1.19.1,1.19.2)"
ordering="NONE"
side="BOTH"