package com.luxtracon.floralis.inits;

import com.luxtracon.floralis.Main;
import com.luxtracon.floralis.items.*;

import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;

import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

import java.util.Objects;

@EventBusSubscriber(modid = Main.MODID)
public class ItemInit
{
	public static ItemSeedFlower seedFlowerWhite;
	public static ItemSeedFlower seedFlowerOrange;
	public static ItemSeedFlower seedFlowerMagenta;
	public static ItemSeedFlower seedFlowerLightBlue;
	public static ItemSeedFlower seedFlowerYellow;
	public static ItemSeedFlower seedFlowerLime;
	public static ItemSeedFlower seedFlowerPink;
	public static ItemSeedFlower seedFlowerGray;
	public static ItemSeedFlower seedFlowerLightGray;
	public static ItemSeedFlower seedFlowerCyan;
	public static ItemSeedFlower seedFlowerPurple;
	public static ItemSeedFlower seedFlowerBlue;
	public static ItemSeedFlower seedFlowerBrown;
	public static ItemSeedFlower seedFlowerGreen;
	public static ItemSeedFlower seedFlowerRed;
	public static ItemSeedFlower seedFlowerBlack;

	public static ItemSeedCactus seedCactusWhite;
	public static ItemSeedCactus seedCactusOrange;
	public static ItemSeedCactus seedCactusMagenta;
	public static ItemSeedCactus seedCactusLightBlue;
	public static ItemSeedCactus seedCactusYellow;
	public static ItemSeedCactus seedCactusLime;
	public static ItemSeedCactus seedCactusPink;
	public static ItemSeedCactus seedCactusGray;
	public static ItemSeedCactus seedCactusLightGray;
	public static ItemSeedCactus seedCactusCyan;
	public static ItemSeedCactus seedCactusPurple;
	public static ItemSeedCactus seedCactusBlue;
	public static ItemSeedCactus seedCactusBrown;
	public static ItemSeedCactus seedCactusGreen;
	public static ItemSeedCactus seedCactusRed;
	public static ItemSeedCactus seedCactusBlack;

	public static ItemPlantParts partsWhite;
	public static ItemPlantParts partsOrange;
	public static ItemPlantParts partsMagenta;
	public static ItemPlantParts partsLightBlue;
	public static ItemPlantParts partsYellow;
	public static ItemPlantParts partsLime;
	public static ItemPlantParts partsPink;
	public static ItemPlantParts partsGray;
	public static ItemPlantParts partsLightGray;
	public static ItemPlantParts partsCyan;
	public static ItemPlantParts partsPurple;
	public static ItemPlantParts partsBlue;
	public static ItemPlantParts partsBrown;
	public static ItemPlantParts partsGreen;
	public static ItemPlantParts partsRed;
	public static ItemPlantParts partsBlack;

	public static ItemPlantPetal petalWhite;
	public static ItemPlantPetal petalOrange;
	public static ItemPlantPetal petalMagenta;
	public static ItemPlantPetal petalLightBlue;
	public static ItemPlantPetal petalYellow;
	public static ItemPlantPetal petalLime;
	public static ItemPlantPetal petalPink;
	public static ItemPlantPetal petalGray;
	public static ItemPlantPetal petalLightGray;
	public static ItemPlantPetal petalCyan;
	public static ItemPlantPetal petalPurple;
	public static ItemPlantPetal petalBlue;
	public static ItemPlantPetal petalBrown;
	public static ItemPlantPetal petalGreen;
	public static ItemPlantPetal petalRed;
	public static ItemPlantPetal petalBlack;

	public static ItemDyedDust dyeWhite;
	public static ItemDyedDust dyeOrange;
	public static ItemDyedDust dyeMagenta;
	public static ItemDyedDust dyeLightBlue;
	public static ItemDyedDust dyeYellow;
	public static ItemDyedDust dyeLime;
	public static ItemDyedDust dyePink;
	public static ItemDyedDust dyeGray;
	public static ItemDyedDust dyeLightGray;
	public static ItemDyedDust dyeCyan;
	public static ItemDyedDust dyePurple;
	public static ItemDyedDust dyeBlue;
	public static ItemDyedDust dyeBrown;
	public static ItemDyedDust dyeGreen;
	public static ItemDyedDust dyeRed;
	public static ItemDyedDust dyeBlack;

	public static ItemDyedClay clayWhite;
	public static ItemDyedClay clayOrange;
	public static ItemDyedClay clayMagenta;
	public static ItemDyedClay clayLightBlue;
	public static ItemDyedClay clayYellow;
	public static ItemDyedClay clayLime;
	public static ItemDyedClay clayPink;
	public static ItemDyedClay clayGray;
	public static ItemDyedClay clayLightGray;
	public static ItemDyedClay clayCyan;
	public static ItemDyedClay clayPurple;
	public static ItemDyedClay clayBlue;
	public static ItemDyedClay clayBrown;
	public static ItemDyedClay clayGreen;
	public static ItemDyedClay clayRed;
	public static ItemDyedClay clayBlack;

	public static ItemPotUnfired potUnfiredWhite;
	public static ItemPotUnfired potUnfiredOrange;
	public static ItemPotUnfired potUnfiredMagenta;
	public static ItemPotUnfired potUnfiredLightBlue;
	public static ItemPotUnfired potUnfiredYellow;
	public static ItemPotUnfired potUnfiredLime;
	public static ItemPotUnfired potUnfiredPink;
	public static ItemPotUnfired potUnfiredGray;
	public static ItemPotUnfired potUnfiredLightGray;
	public static ItemPotUnfired potUnfiredCyan;
	public static ItemPotUnfired potUnfiredPurple;
	public static ItemPotUnfired potUnfiredBlue;
	public static ItemPotUnfired potUnfiredBrown;
	public static ItemPotUnfired potUnfiredGreen;
	public static ItemPotUnfired potUnfiredRed;
	public static ItemPotUnfired potUnfiredBlack;

	public static ItemPotFired potFiredWhite;
	public static ItemPotFired potFiredOrange;
	public static ItemPotFired potFiredMagenta;
	public static ItemPotFired potFiredLightBlue;
	public static ItemPotFired potFiredYellow;
	public static ItemPotFired potFiredLime;
	public static ItemPotFired potFiredPink;
	public static ItemPotFired potFiredGray;
	public static ItemPotFired potFiredLightGray;
	public static ItemPotFired potFiredCyan;
	public static ItemPotFired potFiredPurple;
	public static ItemPotFired potFiredBlue;
	public static ItemPotFired potFiredBrown;
	public static ItemPotFired potFiredGreen;
	public static ItemPotFired potFiredRed;
	public static ItemPotFired potFiredBlack;

	private static void registerRender(Item item)
	{
		ModelLoader.setCustomModelResourceLocation(item, 0, new ModelResourceLocation(Objects.requireNonNull(item.getRegistryName()), "inventory"));
	}

	public static void init()
	{
		seedFlowerWhite = new ItemSeedFlower("whiteseed");
		seedFlowerOrange = new ItemSeedFlower("orangeseed");
		seedFlowerMagenta = new ItemSeedFlower("magentaseed");
		seedFlowerLightBlue = new ItemSeedFlower("lightblueseed");
		seedFlowerYellow = new ItemSeedFlower("yellowseed");
		seedFlowerLime = new ItemSeedFlower("limeseed");
		seedFlowerPink = new ItemSeedFlower("pinkseed");
		seedFlowerGray = new ItemSeedFlower("grayseed");
		seedFlowerLightGray = new ItemSeedFlower("lightgrayseed");
		seedFlowerCyan = new ItemSeedFlower("cyanseed");
		seedFlowerPurple = new ItemSeedFlower("purpleseed");
		seedFlowerBlue = new ItemSeedFlower("blueseed");
		seedFlowerBrown = new ItemSeedFlower("brownseed");
		seedFlowerGreen = new ItemSeedFlower("greenseed");
		seedFlowerRed = new ItemSeedFlower("redseed");
		seedFlowerBlack = new ItemSeedFlower("blackseed");

		seedCactusWhite = new ItemSeedCactus("whitecactusseed");
		seedCactusOrange = new ItemSeedCactus("orangecactusseed");
		seedCactusMagenta = new ItemSeedCactus("magentacactusseed");
		seedCactusLightBlue = new ItemSeedCactus("lightbluecactusseed");
		seedCactusYellow = new ItemSeedCactus("yellowcactusseed");
		seedCactusLime = new ItemSeedCactus("limecactusseed");
		seedCactusPink = new ItemSeedCactus("pinkcactusseed");
		seedCactusGray = new ItemSeedCactus("graycactusseed");
		seedCactusLightGray = new ItemSeedCactus("lightgraycactusseed");
		seedCactusCyan = new ItemSeedCactus("cyancactusseed");
		seedCactusPurple = new ItemSeedCactus("purplecactusseed");
		seedCactusBlue = new ItemSeedCactus("bluecactusseed");
		seedCactusBrown = new ItemSeedCactus("browncactusseed");
		seedCactusGreen = new ItemSeedCactus("greencactusseed");
		seedCactusRed = new ItemSeedCactus("redcactusseed");
		seedCactusBlack = new ItemSeedCactus("blackcactusseed");

		partsWhite = new ItemPlantParts("whiteparts");
		partsOrange = new ItemPlantParts("orangeparts");
		partsMagenta = new ItemPlantParts("magentaparts");
		partsLightBlue = new ItemPlantParts("lightblueparts");
		partsYellow = new ItemPlantParts("yellowparts");
		partsLime = new ItemPlantParts("limeparts");
		partsPink = new ItemPlantParts("pinkparts");
		partsGray = new ItemPlantParts("grayparts");
		partsLightGray = new ItemPlantParts("lightgrayparts");
		partsCyan = new ItemPlantParts("cyanparts");
		partsPurple = new ItemPlantParts("purpleparts");
		partsBlue = new ItemPlantParts("blueparts");
		partsBrown = new ItemPlantParts("brownparts");
		partsGreen = new ItemPlantParts("greenparts");
		partsRed = new ItemPlantParts("redparts");
		partsBlack = new ItemPlantParts("blackparts");

		petalWhite = new ItemPlantPetal("whitepetal");
		petalOrange = new ItemPlantPetal("orangepetal");
		petalMagenta = new ItemPlantPetal("magentapetal");
		petalLightBlue = new ItemPlantPetal("lightbluepetal");
		petalYellow = new ItemPlantPetal("yellowpetal");
		petalLime = new ItemPlantPetal("limepetal");
		petalPink = new ItemPlantPetal("pinkpetal");
		petalGray = new ItemPlantPetal("graypetal");
		petalLightGray = new ItemPlantPetal("lightgraypetal");
		petalCyan = new ItemPlantPetal("cyanpetal");
		petalPurple = new ItemPlantPetal("purplepetal");
		petalBlue = new ItemPlantPetal("bluepetal");
		petalBrown = new ItemPlantPetal("brownpetal");
		petalGreen = new ItemPlantPetal("greenpetal");
		petalRed = new ItemPlantPetal("redpetal");
		petalBlack = new ItemPlantPetal("blackpetal");

		dyeWhite = new ItemDyedDust("whitedye");
		dyeOrange = new ItemDyedDust("orangedye");
		dyeMagenta = new ItemDyedDust("magentadye");
		dyeLightBlue = new ItemDyedDust("lightbluedye");
		dyeYellow = new ItemDyedDust("yellowdye");
		dyeLime = new ItemDyedDust("limedye");
		dyePink = new ItemDyedDust("pinkdye");
		dyeGray = new ItemDyedDust("graydye");
		dyeLightGray = new ItemDyedDust("lightgraydye");
		dyeCyan = new ItemDyedDust("cyandye");
		dyePurple = new ItemDyedDust("purpledye");
		dyeBlue = new ItemDyedDust("bluedye");
		dyeBrown = new ItemDyedDust("browndye");
		dyeGreen = new ItemDyedDust("greendye");
		dyeRed = new ItemDyedDust("reddye");
		dyeBlack = new ItemDyedDust("blackdye");

		clayWhite = new ItemDyedClay("whiteclay");
		clayOrange = new ItemDyedClay("orangeclay");
		clayMagenta = new ItemDyedClay("magentaclay");
		clayLightBlue = new ItemDyedClay("lightblueclay");
		clayYellow = new ItemDyedClay("yellowclay");
		clayLime = new ItemDyedClay("limeclay");
		clayPink = new ItemDyedClay("pinkclay");
		clayGray = new ItemDyedClay("grayclay");
		clayLightGray = new ItemDyedClay("lightgrayclay");
		clayCyan = new ItemDyedClay("cyanclay");
		clayPurple = new ItemDyedClay("purpleclay");
		clayBlue = new ItemDyedClay("blueclay");
		clayBrown = new ItemDyedClay("brownclay");
		clayGreen = new ItemDyedClay("greenclay");
		clayRed = new ItemDyedClay("redclay");
		clayBlack = new ItemDyedClay("blackclay");

		potUnfiredWhite = new ItemPotUnfired("whiteunfiredpot");
		potUnfiredOrange = new ItemPotUnfired("orangeunfiredpot");
		potUnfiredMagenta = new ItemPotUnfired("magentaunfiredpot");
		potUnfiredLightBlue = new ItemPotUnfired("lightblueunfiredpot");
		potUnfiredYellow = new ItemPotUnfired("yellowunfiredpot");
		potUnfiredLime = new ItemPotUnfired("limeunfiredpot");
		potUnfiredPink = new ItemPotUnfired("pinkunfiredpot");
		potUnfiredGray = new ItemPotUnfired("grayunfiredpot");
		potUnfiredLightGray = new ItemPotUnfired("lightgrayunfiredpot");
		potUnfiredCyan = new ItemPotUnfired("cyanunfiredpot");
		potUnfiredPurple = new ItemPotUnfired("purpleunfiredpot");
		potUnfiredBlue = new ItemPotUnfired("blueunfiredpot");
		potUnfiredBrown = new ItemPotUnfired("brownunfiredpot");
		potUnfiredGreen = new ItemPotUnfired("greenunfiredpot");
		potUnfiredRed = new ItemPotUnfired("redunfiredpot");
		potUnfiredBlack = new ItemPotUnfired("blackunfiredpot");

		potFiredWhite = new ItemPotFired("whitefiredpot");
		potFiredOrange = new ItemPotFired("orangefiredpot");
		potFiredMagenta = new ItemPotFired("magentafiredpot");
		potFiredLightBlue = new ItemPotFired("lightbluefiredpot");
		potFiredYellow = new ItemPotFired("yellowfiredpot");
		potFiredLime = new ItemPotFired("limefiredpot");
		potFiredPink = new ItemPotFired("pinkfiredpot");
		potFiredGray = new ItemPotFired("grayfiredpot");
		potFiredLightGray = new ItemPotFired("lightgrayfiredpot");
		potFiredCyan = new ItemPotFired("cyanfiredpot");
		potFiredPurple = new ItemPotFired("purplefiredpot");
		potFiredBlue = new ItemPotFired("bluefiredpot");
		potFiredBrown = new ItemPotFired("brownfiredpot");
		potFiredGreen = new ItemPotFired("greenfiredpot");
		potFiredRed = new ItemPotFired("redfiredpot");
		potFiredBlack = new ItemPotFired("blackfiredpot");
	}
	
	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> event)
	{
		event.getRegistry().registerAll(seedFlowerWhite);
		event.getRegistry().registerAll(seedFlowerOrange);
		event.getRegistry().registerAll(seedFlowerMagenta);
		event.getRegistry().registerAll(seedFlowerLightBlue);
		event.getRegistry().registerAll(seedFlowerYellow);
		event.getRegistry().registerAll(seedFlowerLime);
		event.getRegistry().registerAll(seedFlowerPink);
		event.getRegistry().registerAll(seedFlowerGray);
		event.getRegistry().registerAll(seedFlowerLightGray);
		event.getRegistry().registerAll(seedFlowerCyan);
		event.getRegistry().registerAll(seedFlowerPurple);
		event.getRegistry().registerAll(seedFlowerBlue);
		event.getRegistry().registerAll(seedFlowerBrown);
		event.getRegistry().registerAll(seedFlowerGreen);
		event.getRegistry().registerAll(seedFlowerRed);
		event.getRegistry().registerAll(seedFlowerBlack);

		event.getRegistry().registerAll(seedCactusWhite);
		event.getRegistry().registerAll(seedCactusOrange);
		event.getRegistry().registerAll(seedCactusMagenta);
		event.getRegistry().registerAll(seedCactusLightBlue);
		event.getRegistry().registerAll(seedCactusYellow);
		event.getRegistry().registerAll(seedCactusLime);
		event.getRegistry().registerAll(seedCactusPink);
		event.getRegistry().registerAll(seedCactusGray);
		event.getRegistry().registerAll(seedCactusLightGray);
		event.getRegistry().registerAll(seedCactusCyan);
		event.getRegistry().registerAll(seedCactusPurple);
		event.getRegistry().registerAll(seedCactusBlue);
		event.getRegistry().registerAll(seedCactusBrown);
		event.getRegistry().registerAll(seedCactusGreen);
		event.getRegistry().registerAll(seedCactusRed);
		event.getRegistry().registerAll(seedCactusBlack);

		event.getRegistry().registerAll(partsWhite);
		event.getRegistry().registerAll(partsOrange);
		event.getRegistry().registerAll(partsMagenta);
		event.getRegistry().registerAll(partsLightBlue);
		event.getRegistry().registerAll(partsYellow);
		event.getRegistry().registerAll(partsLime);
		event.getRegistry().registerAll(partsPink);
		event.getRegistry().registerAll(partsGray);
		event.getRegistry().registerAll(partsLightGray);
		event.getRegistry().registerAll(partsCyan);
		event.getRegistry().registerAll(partsPurple);
		event.getRegistry().registerAll(partsBlue);
		event.getRegistry().registerAll(partsBrown);
		event.getRegistry().registerAll(partsGreen);
		event.getRegistry().registerAll(partsRed);
		event.getRegistry().registerAll(partsBlack);

		event.getRegistry().registerAll(petalWhite);
		event.getRegistry().registerAll(petalOrange);
		event.getRegistry().registerAll(petalMagenta);
		event.getRegistry().registerAll(petalLightBlue);
		event.getRegistry().registerAll(petalYellow);
		event.getRegistry().registerAll(petalLime);
		event.getRegistry().registerAll(petalPink);
		event.getRegistry().registerAll(petalGray);
		event.getRegistry().registerAll(petalLightGray);
		event.getRegistry().registerAll(petalCyan);
		event.getRegistry().registerAll(petalPurple);
		event.getRegistry().registerAll(petalBlue);
		event.getRegistry().registerAll(petalBrown);
		event.getRegistry().registerAll(petalGreen);
		event.getRegistry().registerAll(petalRed);
		event.getRegistry().registerAll(petalBlack);

		event.getRegistry().registerAll(dyeWhite);
		event.getRegistry().registerAll(dyeOrange);
		event.getRegistry().registerAll(dyeMagenta);
		event.getRegistry().registerAll(dyeLightBlue);
		event.getRegistry().registerAll(dyeYellow);
		event.getRegistry().registerAll(dyeLime);
		event.getRegistry().registerAll(dyePink);
		event.getRegistry().registerAll(dyeGray);
		event.getRegistry().registerAll(dyeLightGray);
		event.getRegistry().registerAll(dyeCyan);
		event.getRegistry().registerAll(dyePurple);
		event.getRegistry().registerAll(dyeBlue);
		event.getRegistry().registerAll(dyeBrown);
		event.getRegistry().registerAll(dyeGreen);
		event.getRegistry().registerAll(dyeRed);
		event.getRegistry().registerAll(dyeBlack);

		event.getRegistry().registerAll(clayWhite);
		event.getRegistry().registerAll(clayOrange);
		event.getRegistry().registerAll(clayMagenta);
		event.getRegistry().registerAll(clayLightBlue);
		event.getRegistry().registerAll(clayYellow);
		event.getRegistry().registerAll(clayLime);
		event.getRegistry().registerAll(clayPink);
		event.getRegistry().registerAll(clayGray);
		event.getRegistry().registerAll(clayLightGray);
		event.getRegistry().registerAll(clayCyan);
		event.getRegistry().registerAll(clayPurple);
		event.getRegistry().registerAll(clayBlue);
		event.getRegistry().registerAll(clayBrown);
		event.getRegistry().registerAll(clayGreen);
		event.getRegistry().registerAll(clayRed);
		event.getRegistry().registerAll(clayBlack);

		event.getRegistry().registerAll(potUnfiredWhite);
		event.getRegistry().registerAll(potUnfiredOrange);
		event.getRegistry().registerAll(potUnfiredMagenta);
		event.getRegistry().registerAll(potUnfiredLightBlue);
		event.getRegistry().registerAll(potUnfiredYellow);
		event.getRegistry().registerAll(potUnfiredLime);
		event.getRegistry().registerAll(potUnfiredPink);
		event.getRegistry().registerAll(potUnfiredGray);
		event.getRegistry().registerAll(potUnfiredLightGray);
		event.getRegistry().registerAll(potUnfiredCyan);
		event.getRegistry().registerAll(potUnfiredPurple);
		event.getRegistry().registerAll(potUnfiredBlue);
		event.getRegistry().registerAll(potUnfiredBrown);
		event.getRegistry().registerAll(potUnfiredGreen);
		event.getRegistry().registerAll(potUnfiredRed);
		event.getRegistry().registerAll(potUnfiredBlack);

		event.getRegistry().registerAll(potFiredWhite);
		event.getRegistry().registerAll(potFiredOrange);
		event.getRegistry().registerAll(potFiredMagenta);
		event.getRegistry().registerAll(potFiredLightBlue);
		event.getRegistry().registerAll(potFiredYellow);
		event.getRegistry().registerAll(potFiredLime);
		event.getRegistry().registerAll(potFiredPink);
		event.getRegistry().registerAll(potFiredGray);
		event.getRegistry().registerAll(potFiredLightGray);
		event.getRegistry().registerAll(potFiredCyan);
		event.getRegistry().registerAll(potFiredPurple);
		event.getRegistry().registerAll(potFiredBlue);
		event.getRegistry().registerAll(potFiredBrown);
		event.getRegistry().registerAll(potFiredGreen);
		event.getRegistry().registerAll(potFiredRed);
		event.getRegistry().registerAll(potFiredBlack);
	}
	
	@SubscribeEvent
	public static void registerRenders(ModelRegistryEvent event)
	{
		registerRender(seedFlowerWhite);
		registerRender(seedFlowerOrange);
		registerRender(seedFlowerMagenta);
		registerRender(seedFlowerLightBlue);
		registerRender(seedFlowerYellow);
		registerRender(seedFlowerLime);
		registerRender(seedFlowerPink);
		registerRender(seedFlowerGray);
		registerRender(seedFlowerLightGray);
		registerRender(seedFlowerCyan);
		registerRender(seedFlowerPurple);
		registerRender(seedFlowerBlue);
		registerRender(seedFlowerBrown);
		registerRender(seedFlowerGreen);
		registerRender(seedFlowerRed);
		registerRender(seedFlowerBlack);

		registerRender(seedCactusWhite);
		registerRender(seedCactusOrange);
		registerRender(seedCactusMagenta);
		registerRender(seedCactusLightBlue);
		registerRender(seedCactusYellow);
		registerRender(seedCactusLime);
		registerRender(seedCactusPink);
		registerRender(seedCactusGray);
		registerRender(seedCactusLightGray);
		registerRender(seedCactusCyan);
		registerRender(seedCactusPurple);
		registerRender(seedCactusBlue);
		registerRender(seedCactusBrown);
		registerRender(seedCactusGreen);
		registerRender(seedCactusRed);
		registerRender(seedCactusBlack);

		registerRender(partsWhite);
		registerRender(partsOrange);
		registerRender(partsMagenta);
		registerRender(partsLightBlue);
		registerRender(partsYellow);
		registerRender(partsLime);
		registerRender(partsPink);
		registerRender(partsGray);
		registerRender(partsLightGray);
		registerRender(partsCyan);
		registerRender(partsPurple);
		registerRender(partsBlue);
		registerRender(partsBrown);
		registerRender(partsGreen);
		registerRender(partsRed);
		registerRender(partsBlack);

		registerRender(petalWhite);
		registerRender(petalOrange);
		registerRender(petalMagenta);
		registerRender(petalLightBlue);
		registerRender(petalYellow);
		registerRender(petalLime);
		registerRender(petalPink);
		registerRender(petalGray);
		registerRender(petalLightGray);
		registerRender(petalCyan);
		registerRender(petalPurple);
		registerRender(petalBlue);
		registerRender(petalBrown);
		registerRender(petalGreen);
		registerRender(petalRed);
		registerRender(petalBlack);

		registerRender(dyeWhite);
		registerRender(dyeOrange);
		registerRender(dyeMagenta);
		registerRender(dyeLightBlue);
		registerRender(dyeYellow);
		registerRender(dyeLime);
		registerRender(dyePink);
		registerRender(dyeGray);
		registerRender(dyeLightGray);
		registerRender(dyeCyan);
		registerRender(dyePurple);
		registerRender(dyeBlue);
		registerRender(dyeBrown);
		registerRender(dyeGreen);
		registerRender(dyeRed);
		registerRender(dyeBlack);

		registerRender(clayWhite);
		registerRender(clayOrange);
		registerRender(clayMagenta);
		registerRender(clayLightBlue);
		registerRender(clayYellow);
		registerRender(clayLime);
		registerRender(clayPink);
		registerRender(clayGray);
		registerRender(clayLightGray);
		registerRender(clayCyan);
		registerRender(clayPurple);
		registerRender(clayBlue);
		registerRender(clayBrown);
		registerRender(clayGreen);
		registerRender(clayRed);
		registerRender(clayBlack);

		registerRender(potUnfiredWhite);
		registerRender(potUnfiredOrange);
		registerRender(potUnfiredMagenta);
		registerRender(potUnfiredLightBlue);
		registerRender(potUnfiredYellow);
		registerRender(potUnfiredLime);
		registerRender(potUnfiredPink);
		registerRender(potUnfiredGray);
		registerRender(potUnfiredLightGray);
		registerRender(potUnfiredCyan);
		registerRender(potUnfiredPurple);
		registerRender(potUnfiredBlue);
		registerRender(potUnfiredBrown);
		registerRender(potUnfiredGreen);
		registerRender(potUnfiredRed);
		registerRender(potUnfiredBlack);

		registerRender(potFiredWhite);
		registerRender(potFiredOrange);
		registerRender(potFiredMagenta);
		registerRender(potFiredLightBlue);
		registerRender(potFiredYellow);
		registerRender(potFiredLime);
		registerRender(potFiredPink);
		registerRender(potFiredGray);
		registerRender(potFiredLightGray);
		registerRender(potFiredCyan);
		registerRender(potFiredPurple);
		registerRender(potFiredBlue);
		registerRender(potFiredBrown);
		registerRender(potFiredGreen);
		registerRender(potFiredRed);
		registerRender(potFiredBlack);
	}
}